name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Rust MUSL Builder
        uses: NSCoder/rust-musl-action@v1.0.0
          args: cargo build --target x86_64-unknown-linux-musl --release
