name: srun-helper-rs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: 'compile'
        uses: heroku/rust-cargo-musl-action@v1
        with:
          command: 'build'
          flags: '--features vendored-openssl'
      - uses: actions/upload-artifact@v2
        with:
          name: srun-helper-rs
          path: ${{ steps.compile.outputs.release-dir }}/srun-helper-rs
